// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onTriggerChange();

float humidity;
float temperature;
int moisture;
int trigger;
bool pump;

void initProperties(){

  ArduinoCloud.addProperty(humidity, READ, 120 * SECONDS, NULL);
  ArduinoCloud.addProperty(temperature, READ, 120 * SECONDS, NULL);
  ArduinoCloud.addProperty(moisture, READ, 5 * SECONDS, NULL);
  ArduinoCloud.addProperty(trigger, READWRITE, ON_CHANGE, onTriggerChange);
  ArduinoCloud.addProperty(pump, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
